### ISSUE TITLE
Suggestion: Handling of SAM optional tags

### ISSUE THREAD

**Issue by nh13** [brentp/hts-nim#10]
I admit, I have zero  experience in NIM, but I am just looking through the API, and had a thought: could there be a `get` method that returns an `Option[T]` with the correct type?  I'd find this much more convenient than having to check if the return value is `nil`.  Or at least it satisfies my functional programming style since I can map/filter on it (_I think_).  I'd love to see the following methods:
```
# assignment of a tag, overwrites an existing value
rec[int]("NM") = 2 
# comparison of a tag, required to exist
rec[int]("NM") == 2
# could be none or some(2)
rec.get[int]("NM")
```
Hopefully this makes sense.  It likely can be applied to the VCF API as well.

**Comment by brentp** [comment]
I like this idea. nim syntax would require that to read as : tag[int](rec, "NM"), so for now, in the api branch, I have `rec.int_tag("SM")`, `rec.string_tag("RG")` there are functional libraries for Nim that will let you get all `some`s from iterables of `maybe`s so I don't think automatically returning the unwrapped int is needed.

**Comment by brentp** [comment]
in nearly all cases, the user knows the type of the tag, so this api is preferable as it remove a level of checks. Originally there was 1 check to see if the tag existed and another to see if the option contained a value. This API leaves only 1 check to see if the option contains a value. With this, it's not possible to tell that the tag does not exist. I'm going to keep it in the `api` branch and see how it feels in my daily programming. I think I might prefer the original for explicit behavior over this one for brevity, but we'll see.

**Comment by brentp** [comment]
this has been merged into master. despite the odd syntax, I went for the `tag[int](rec, "NM")` syntax as this is brief and idiomatic nim.
thanks for the idea. I think this is a nice change.
