### ISSUE TITLE
Names for Op and CigarOp are confusing at first glance

### ISSUE THREAD

**Issue by nh13** [brentp/hts-nim#11]
It looks like `Op` stores both the `CigarOp` and length, but why not rename `Op` to `CigarElem` or `CigarTuple`.  `Op` seems too general, and doesn't imply length.  Thoughts?

**Comment by brentp** [comment]
Agree. What do you think about `Element`?

**Comment by nh13** [comment]
Element of what?

**Comment by brentp** [comment]
I changed to CigarElement in the api branch. I like this change. Will keep it and merge after more testing.

**Comment by brentp** [comment]
this is now in master.
