### ISSUE TITLE
Question: whats the "back" value represent in CigarOp?

### ISSUE THREAD

**Issue by nh13** [brentp/hts-nim#12]
I don't see it in samtools.github.io/hts-specs/SAMv1.pdf

**Comment by brentp** [comment]
Thanks for the issues, I'll have a look at each. This one is easy. It just allows to skip backwards on the reference. It consumes no query sequence and negative reference sequence.

Not sure about the spec.

**Comment by nh13** [comment]
I would folks looking at matching possible types would get confused at an operator that is not in the SAM spec though.
