### ISSUE TITLE
Question: what is the SAM_RGAUX flag?

### ISSUE THREAD

**Issue by nh13** [brentp/hts-nim#13]
I don't see it in the SAM spec.  Is it related to long reads (cigars)?  https://github.com/samtools/hts-specs/issues/40

**Comment by brentp** [comment]
I would guess that it lets the user decide if they want to decode the read-group aux fields from from CRAM.

I am closing this as the API for htslib is quite large, the goal of hts-nim is to allow access to all of it for savvy users while providing a simple API for the most-used parts.
