### ISSUE TITLE
qual is ambiguous, reconsider naming to mapq or mapping_quality

### ISSUE THREAD

**Issue by nh13** [brentp/hts-nim#14]
You already have a long name for `base_qualities`.  I also don't see in the API (https://brentp.github.io/hts-nim/hts/bam.html) how to retrieve the bases or base qualities.

**Comment by brentp** [comment]
yes, I've actually been hit by this. I have renamed to `mapping_quality`.

**Comment by brentp** [comment]
this is now in master and qual is deprecated.
