### ISSUE TITLE
Does this library work with SAM files?

### ISSUE THREAD

**Issue by nellore** [brentp/hts-nim#17]
I seem to be running into the error at https://github.com/brentp/hts-nim/blob/master/src/hts/bam.nim#L242 when I try to open a SAM file. Am I doing something silly, or is SAM not supported yet?

Thanks!
A

**Comment by brentp** [comment]
thanks for reporting this. I hadn't noticed this but I just pushed a fix.
please let me know if you have any more issues or questions.

**Comment by nellore** [comment]
Thanks for getting on this so fast! I don't think the issue is resolved yet; I don't get any records when I try to iterate over a SAM. So the new test in `bamtest.nim` doesn't iterate over any records and necessarily succeeds, at least on my Macbook.

**Comment by brentp** [comment]
well, that was sloppy of me. It actually iterates now. thanks for persisting.

**Comment by nellore** [comment]
Woooorks! Thanks so much for this slice of awesome.

A

**Comment by brentp** [comment]
sure. let me know if you hit any other issues. there are definitely parts that have not been exercised.
