### ISSUE TITLE
Q: how to read BAM from internally generated stream

### ISSUE THREAD

**Issue by andreas-wilm** [brentp/hts-nim#25]
Hi Brent,

what's the recommended way to parse internally generated BAM streams? The use case here is that I call BWA internally using `osproc`, returning lines on stdout as iterator. `open()` can't be used, unless I use a named pipe as intermediate. Is there a way to generate a Record from a SAM/BAM line?

Thanks,
Andreas

**Comment by brentp** [comment]
You could do this with `sam_hdr_parse` for the header and `sam_parse1` for the records. I'll see about making this more convenient.

**Comment by brentp** [comment]
I am implementing this in hts-nim now so it'll be more ergonomic to accomplish. Should have it up today.

**Comment by brentp** [comment]
I just pushed methods for making this simpler. See the tests added in a95d8f1 for an example.

**Comment by brentp** [comment]
thanks for following up, glad it worked for you. I think `Header` is the proper name in both cases and specifying `vcf.Header` is an understandable change. I could have namespaced so  that importing specific packages was required, but I didn't do that by accident and now I prefer it that way.
