### ISSUE TITLE
Undocumented and possibly broken functions

### ISSUE THREAD

**Issue by sodic** [brentp/hts-nim#26]
Hello,

I've been working with `hts-nim` at GIS with @andreas-wilm.

I believe the documentation needs an update. I've encountered a couple of undocumented (but implemented) functions (e.g. `base_at` from the _bam.nim_ module and the `[]` operator in the _fai.nim_ module). The dynamic functionalities of the doc pages (search, group by...) are broken as well because the HTML relies on a missing a JavaScript file. However, this seems to be a problem with Nim's `docgen` package rather than with `hts-nim`. I've [opened an issue aiming to get this fixed](https://github.com/nim-lang/Nim/issues/8952) and it is probably a good idea to update the docs when they to :).

One more thing regarding the `[]` operator for `Fai` objects. It produces some strange results. Let's say we have a file called _sample.fa_ with the following content:
```
>ref
ACGGTCGA
```
The following two programs execute normally:
```nim
import hts

var fai: Fai
discard open(fai, "sample.fa")
echo fai[0] # ouputs 'ref'
```
```nim
import hts

var fai: Fai
discard open(fai, "sample.fa")
echo fai.get("ref", 0, 2) # outputs 'ACG'
```
Hovewer, the following program fails with an error as if the `[]` call has consumed the reference somehow:
```nim
import hts

var fai: Fai
discard open(fai, "sample.fa")
echo fai[0]
echo fai.get("ref", 0, 2)
```
Similar strange behavior can be observed like this:
```nim
echo fai[0] # outputs 'ref'
echo fai[0] # outputs an empty string
echo fai[0] # outputs some junk, subsequent calls eventually detect a segmentation fault
```

Thanks,
Filip

**Comment by brentp** [comment]
thanks for reporting. I just pushed a fix for the issue with `Fai`. I will update the docs today.

please continue to let me know as you find problems like this. there are likely easily fixed bugs like this in areas of the API that I use less.
