### ISSUE TITLE
Q: best practices to read vcf from stdin or string

### ISSUE THREAD

**Issue by andreas-wilm** [brentp/hts-nim#27]
Hey Brent,

it might be something obvious that I'm overlooking, but what would be considered best practice to parse a vcf from stdin or a string (generated from within Nim). Will I have to convert it to a temp file first to be able to use vcf.open?

Thanks,
Andreas

**Comment by brentp** [comment]
Hi Andreas, you can use "/dev/stdin" or just "-" to open a VCF from stdin.
Let me know any other questions.

**Comment by andreas-wilm** [comment]
Oh. I thought I had tried. Thanks.

The currently more important one would be to be able to parse from a string that a function generated. Possible?

**Comment by brentp** [comment]
yes. see: https://brentp.github.io/hts-nim/hts/vcf.html#from_string,Variant,Header,string

you'll still need a valid header, but it can parse directly from string.
