### ISSUE TITLE
conditional iterator

### ISSUE THREAD

**Issue by danielecook** [brentp/hts-nim#37]
Is there a way to iterate over a VCF by region OR in its entirety?

I'm trying to make supplying a region optional. So something like this:

```nim
    doAssert open(v, vcf)
    var records = if region.len > 0:
        v.query(region)
    else:
        v

    for rec in records:
        echo rec
```

However, I keep running into type errors. How can I return a 'blank' query that returns all records?

**Comment by brentp** [comment]
i just use this:
https://github.com/brentp/slivar/blob/master/src/slivarpkg/evaluator.nim#L28

**Comment by danielecook** [comment]
Thanks!

**Comment by brentp** [comment]
I could make `query` default to iterating over the entire VCF when given the empty string...

**Comment by danielecook** [comment]
That would be a good idea but I like the implementation that makes use of the region file too. I am picking up nim b/c of this library and thus far it's been great! Thanks for putting it together.

**Comment by brentp** [comment]
glad to hear it. I'm happy to answer any other questions.
