### ISSUE TITLE
modify qname

### ISSUE THREAD

**Issue by Rachael-rq** [brentp/hts-nim#41]
Hi Brent,

I'm wondering if there is any easy way to modify a record.qname as I would like to add additional information to it.

Cheers,
Ruqian

**Comment by brentp** [comment]
I agree this would be nice to have. But, it is actually not trivial as it requires updating the entire bam record. You can see how pysam does it [here](https://github.com/pysam-developers/pysam/blob/master/pysam/libcalignedsegment.pyx#L1159-L1200)
I would gladly accept a PR for this. If not, I will have a look soon.

**Comment by brentp** [comment]
I went ahead and added this as `set_qname(r:Record, qname:string)`
please let me know any problems. Thanks for the suggestion.

**Comment by Rachael-rq** [comment]
Thanks for that,  I tested that add it works well!
