### ISSUE TITLE
set tag/ append tag

### ISSUE THREAD

**Issue by Rachael-rq** [brentp/hts-nim#42]
Hi Brent,

Could we also have a `set_tag` or `append_tag()` function?

Thanks,
Ruqian

**Comment by brentp** [comment]
this has been added. just use, e.g.:
```
aln.set_tag("AS", 22)
```

let me know any problems, and please continue to open issues for stuff like this. As you can tell, some of the stuff to write/update records is missing. I am happy to add that, I just haven't needed most of it yet.
