### ISSUE TITLE
Request: addition to wiki/Examples

### ISSUE THREAD

**Issue by andreas-wilm** [brentp/hts-nim#43]
Hi Brent, 

not an issue as such, just wanted to ask whether you would consider adding a little (and not particularly sophisticated) [FastQ decontamination tool](https://bitbucket.org/andreas-wilm/decontanimate/src/master/) I wrote a while back to [your examples listed in the wiki](https://github.com/brentp/hts-nim/wiki/Examples).

Thanks, Andreas

**Comment by brentp** [comment]
absolutely! I have just added it. Let me know if the description is OK.

**Comment by brentp** [comment]
looks like nice, clean nim code.

**Comment by andreas-wilm** [comment]
Wow. Thanks a lot. Just one thing: the tool is called deconta**nim**ate, not deconta**min**ate  :)

**Comment by brentp** [comment]
fixed! thanks!
