### ISSUE TITLE
How to build new variants?

### ISSUE THREAD

**Issue by kmhernan** [brentp/hts-nim#55]
So I was wondering if you had some good examples of building new variant objects? My case is having n vcfs that i'm trying to merge into 1. Even just a naive merge where i only keep info/format from 1 vcf cause I can assume in this case all vcfs have the same loci in it just different samples. Trying to build that new variant from scratch is not clear to me and I'm not confident copying one variant and trying to update `variant.c` `variant.vcf` etc is safe really. I guess I was thinking that I would be able to make a new empty variant from a vcf object or vcf header object, since I can easily make my new VCF with the right header etc. Anyways, if you could point me to some examples of building new variants i'd appreciate it.

**Comment by brentp** [comment]
hi Kyle, I would use [hts-nim-sugar](https://github.com/mflevine/hts-nim-sugar) from @mflevine  for that.
if you dont want to use that for some reason, you can have a look at the `from_string` methods. these are less than ideal, but provide a pretty simple way to make new variants. 
happy to answer other questions if you encounter any problems.

**Comment by kmhernan** [comment]
Hey thanks. A quick look at that seems like it will get me what I need. Closing this.

**Comment by kmhernan** [comment]
Some deeper diving @brentp it seems like a change was made to `bcf_update_alleles_str` in this commit https://github.com/brentp/hts-nim/commit/5da0f8548305b331017e3e496ae99c040708b2dd#diff-f29bbe1e8ea76c6a3a8ac828ec0361d0R815

instead of passing alleles as a `cstring` (which is also how @mflevine wrote hts-nim-sugar to work) it was changed to `ptr cstringArray`

In `htc_concat.h` here https://github.com/brentp/hts-nim/blob/fe27ca9a624078f7db9a76de567888019cc1f7f4/src/hts/private/hts_concat.h#L696 I see the prototype of

```
int bcf_update_alleles_str(const bcf_hdr_t *hdr, bcf1_t *line, char ***dst);
```

When you look in htslib though (https://github.com/samtools/htslib/blob/develop/vcf.c#L4135):
```
int bcf_update_alleles_str(const bcf_hdr_t *hdr, bcf1_t *line, const char *alleles_string)
```

I have attempted to use `allocCStringArray` and pass the `myCstringArray.addr` as that parameter which doesn't throw an error, but the allele slots are definitely messed up in the generated variant object. Not sure if this is cause I'm not making the `cstringArray` correctly, or if it shouldn't be a `ptr cstringArray` at all ?

**Comment by brentp** [comment]
hts-nim is not compatible with `develop` as it contains API-breaking changes. You'll have to checkout htslib v1.9 or less. I have #53 open to update hts-nim to support the recent changes once htslib 1.10 comes out, but that is not likely to happen fully before the new year.

**Comment by kmhernan** [comment]
Hmm i am actually using htslib v1.9 and it is still defined the same way https://github.com/samtools/htslib/blob/1.9/vcf.c#L3617

Here is something that uses some of the logic from hts-nim-sugar and reproduces my issues:

```
import hts/vcf
import sequtils
from strutils import join
import hts/private/hts_concat

proc init_header*(h: var Header, samples:seq[string] = @[]) =
  ## initialize an empty VCF header
  var default_header = ("""##fileformat=VCFv4.2
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT""")
  if len(samples) != 0:
    default_header &= " " & samples.join("      ")
  h.from_string(default_header)

proc add_contig*(h:Header, ID:string, meta:tuple = ()): Status =
  ## add a contig field to the header with the given values
  var str = "##contig=<ID=" & ID
  for key, value in fieldPairs(meta):
    str &= "," & key & "=" & value
  return h.add_string(str & ">")

proc add_filters*(v:Variant, filters:seq[string]) =
  # add filter flags to variant
  var filter_id: cint
  for filter in filters:
    filter_id = bcf_hdr_id2int(v.vcf.header.hdr, BCF_DT_ID, filter)
    doAssert bcf_add_filter(v.vcf.header.hdr, v.c, filter_id) == 1, "error adding filter"

proc new_variant*(v:VCF, contig: string, pos1: int32, id: string= ".", REF:string=".", ALT:string=".", qual:float = 0, filters:seq[string] = @[]): Variant =
  # create a new variant for VCF with the given values (base-1 position).
  result = newVariant()
  result.vcf = v
  result.c.rid = bcf_hdr_name2id(result.vcf.header.hdr, contig)
  result.c.pos = pos1 - 1
  result.c.d.id = id
  var
    als = REF & "," & ALT
    sarr = allocCStringArray([als])
  doAssert bcf_update_alleles_str(result.vcf.header.hdr, result.c, sarr.addr) == 0, "error adding alleles"
  result.c.qual = qual
  result.add_filters(filters)
  deallocCStringArray(sarr)

when isMainModule:
  var
    h:Header
    v:VCF

  init_header(h)
  doAssert h.add_contig("1",(species:"Human")) == Status.OK
  if not open(v, "test.vcf.gz", mode="w"):
      quit "could not open vcf"
  v.header = h
  discard v.write_header()

  var
    vr = v.new_variant("1", int32(1), ".", "A", "T")
  echo vr.REF
  echo vr.ALT
  discard v.write_variant(vr)
  v.close
```

This will produce problematic alleles. I have tried to setup the `cstringArray` in many different ways and it still is a problem. Thoughts?

**Comment by brentp** [comment]
hmm. looks like you're right. can you try updating `bcf_update_alleles_str` to use a cstring? not sure why c2nim changed to use a cstringArray for that.
so after that change, i'd try passing `als.cstring`

I'll be able to look at this in detail on monday.

**Comment by kmhernan** [comment]
Yup worked. I wasn't expecting any response until next week anyways haha so no problem. Thanks for you help, and happy holidays.

**Comment by brentp** [comment]
I pushed a fix for this. thanks for digging in.
using `variant.REF = "A"` and `variant.ALT = @["CC"]`
are now supported.

happy holidays to you too.
