### ISSUE TITLE
Issue with vcf.nim when running nimble test or importing

### ISSUE THREAD

**Issue by NatPRoach** [brentp/hts-nim#58]
Hello,
I'm running into a problem using hts-nim. Upon downloading the git repo and using `nimble install` it seems to install fine, but upon running `nimble test`, or attempting to `import hts` in any of my nim scripts, I'm getting the following error:

```
/Users/nproach/Documents/src/hts-nim/src/hts/vcf.nim(202, 35) Error: undeclared identifier: 'csize_t'
stack trace: (most recent call last)
/private/var/folders/84/b9w2y49j5v55sc9sq9tn4qkm0000gn/T/nimblecache/nimscriptapi.nim(165, 16)
/Users/nproach/Documents/src/hts-nim/hts_1286.nims(25, 8) testTask
/usr/local/Cellar/nim/1.0.0/nim/lib/system/nimscript.nim(252, 7) exec
/usr/local/Cellar/nim/1.0.0/nim/lib/system/nimscript.nim(252, 7) Error: unhandled exception: FAILED: nim c  -d:useSysAssert -d:useGcAssert --lineDir:on --debuginfo -r tests/all [OSError]
     Error: Exception raised during nimble script execution
```

I'd appreciate any help you can provide on fixing this issue. Thanks!

**Comment by brentp** [comment]
hi, I just pushed a change for this. Recent versions of nim are expecting csize_t, but this should be fixed for nim 1.0.0 if you git pull.

**Comment by NatPRoach** [comment]
That seems to have fixed it! Thanks!

**Comment by brentp** [comment]
great! thanks for reporting.
