### ISSUE TITLE
can't clone project properly

### ISSUE THREAD

**Issue by unikzforce** [brentp/hts-nim#6]
I just cant clone the project properly:
![hts-nim-git-clone](https://user-images.githubusercontent.com/7010566/33323348-7d4a9f74-d461-11e7-81e9-2e36dd19de28.PNG)

even when i download it without cloning , can't extract it, it says hts/aux.nim no such file

**Comment by brentp** [comment]
I would remove the directory completely and re-clone. hts/aux.nim is there are you can see browsing the github repo.

**Comment by unikzforce** [comment]
thanks, i've just copied hts/aux.nim from browser.

**Comment by brentp** [comment]
I have renamed that file so this should no longer be an issue.
