### ISSUE TITLE
Multiple iterators with items*(v:VCF)

### ISSUE THREAD

**Issue by cvlvxi** [brentp/hts-nim#60]
Hi Brent,

I've been wondering about whether it would be possible to open two VCF such that instead of iterating through the items like such

```
var v_genome: VCF 
var v_exome: VCF

discard v_genome.open(hg19_genome)
discard v_exome.open(hg19_exome)

for record in v_genome:
...
```

I can store the items iterator in a variable -- but I think that requires a `{.closure.}` pragma? (new to nim). I tried this out by copying the items proc in vcf.nim and just adding a closure pragma

```
iterator item_closure*(v:VCF): Variant {.closure.} =
  ## Each returned Variant has a pointer in the underlying iterator
  ## that is updated each iteration; use .copy to keep it in memory

  # all iterables share the same variant
  var variant: Variant
  new(variant, destroy_variant)

  while true:
    if bcf_read(v.hts, v.header.hdr, v.c) == -1:
      break
    discard bcf_unpack(v.c, 1 or 2)
    variant.vcf = v
    variant.c = v.c
    yield variant
  # allow an error code of 1 (CTG_UNDEF) because we can have a contig
  # undefined in the reader in the absence of an index or a full header
  # but that's not an error in this library.
  if v.c.errcode > 1:
    stderr.write_line "hts-nim/vcf bcf_read error:" & $v.c.errcode
    stderr.write_line "last read variant:", variant.tostring()
    quit(2)
```

I then was able to do the following:

```
var v_genome: VCF 
var v_exome: VCF

discard v_genome.open(hg19_genome)
discard v_exome.open(hg19_exome)

var i1 = item_closure
var i2 = item_closure
while true:
    let v_g: Variant = i1(v_genome)
    let v_e: Variant = i2(v_exome)

    if finished(i1):
        echo "Genome Finished"
    
    if finished(i2):
        echo "Exome Finished"

    if finished(i1) and finished(i2):
        break

```

And it seems to work as I intended...

Would you consider adding a seperate iterator specifically just to allow this? Or is there another way to do this that i'm missing (again new to nim!)

**Comment by brentp** [comment]
hi, that seems a reasonable use-case. There is a performance overhead to `closure` so I'd prefer it wasn't the default, but I tried the code below, which just makes a closure iterator to wrap the default iterator and it seems to work. Does that cover your use-case?
```nim
import hts/vcf

iterator variants*(v:VCF): Variant {.closure.} =
  for variant in v: yield variant

when isMainModule:
  import os
  var ivcf:VCF
  doAssert ivcf.open(paramStr(1))

  var it = variants
  echo it(ivcf)
  echo it(ivcf)
```

**Comment by cvlvxi** [comment]
Ah that's exactly what I wanted to write :D

Thanks!

**Comment by brentp** [comment]
great! took me a minute to figure out it was that simple. happy to answer any other questions.
