### ISSUE TITLE
hts-1.10 assertion failed

### ISSUE THREAD

**Issue by slw287r** [brentp/hts-nim#62]
Hi Brent,

I `nimble install hts` hts-0.3.4 and `doAssert minor >= 10` failed in hts.nim

```
Error: unhandled exception: ~/.nimble/pkgs/hts-0.3.4/hts.nim(31, 12) `minor >= 10` [hts/nim] error this version of hts-nim requires htslib >=1.10, got version: 1.9 [AssertionError]
```

I temporally disabled this assertion to get jigv to work on macOS which the static binary release does support.

Thanks,
Richard

**Comment by brentp** [comment]
hi, thanks for giving it a try. That means you need to update your htslib version. The versions 1.10 and greater are incompatible with < 1.10 and hts-nim only supports >= 1.10.
would love to have a brew recipe or osx static build if you get it going.

**Comment by slw287r** [comment]
Thank you Brent, jigv runs smoothly after I upgrade my system htslib to 1.10.2.

**Comment by brentp** [comment]
excellent. happy to hear any feedback.
