### ISSUE TITLE
Write to bam/cram instead of sam

### ISSUE THREAD

**Issue by mflevine** [brentp/hts-nim#64]
Right now if I try to write a bam file, it will only output uncompressed SAM. Is it possible to support writing BAMs and possibly CRAM too?

**Comment by brentp** [comment]
if you use mode="wb", it will write bam, mode="wc" it will be cram. I'll add a change to detect file extension and set these automatically if mode == "w".

**Comment by mflevine** [comment]
Awesome thanks!

**Comment by brentp** [comment]
auto-detect bam/cram writer (as was already implemented for vcf/bcf) is now in latest tag.
thanks for reporting.
