### ISSUE TITLE
No public facing method for closing Fai file

### ISSUE THREAD

**Issue by NatPRoach** [brentp/hts-nim#70]
Hello,
I may be missing something obvious but the documentation doesn't seem to have a method for closing an Fai object once you've opened it. Is that intentional or is there anyway to expose such a method?
Thanks a bunch for the library, it's been super helpful!

**Comment by brentp** [comment]
Hi, I didn't expose that. It gets closed when the fai object gets garbage collected. I have just added it in case you really need to keep filehandles closed without depending on GC.

Glad to hear it's useful!

**Comment by brentp** [comment]
BTW, I added your project here: https://github.com/brentp/hts-nim/wiki/Example-uses-of-hts-nim 
Nice work!

**Comment by NatPRoach** [comment]
> BTW, I added your project here: https://github.com/brentp/hts-nim/wiki/Example-uses-of-hts-nim
> Nice work!

Thanks a bunch for the fast turn around on this issue and for adding conduit to the wiki! I appreciate it!
