### ISSUE TITLE
Version tag in 0.3.13 is wrong

### ISSUE THREAD

**Issue by Benjamin-Lee** [brentp/hts-nim#71]
I'm trying to use the new version but it seems that Nimble won't install it. From looking closer, the version tagged 0.3.13's hts.nimble file has the version as 0.3.12:

https://github.com/brentp/hts-nim/blob/3c4ce10417faf86c70ddd3467930d7e5a9af847b/hts.nimble#L3

```
~/D/P/R/test ❯❯❯ nimble install hts@0.3.13
    Reading official package list
Downloading https://github.com/brentp/hts-nim using git
    Cloning latest tagged version: v0.3.13
     Error: Downloaded package's version does not satisfy requested version range: wanted 0.3.13 got 0.3.12.
```

**Comment by brentp** [comment]
my bad. fixed by tagging version 0.3.14 (correctly).
thanks for reporting.
